### ISSUE TITLE
Area editing: Unreasonable error

### ISSUE THREAD

**Issue by arnelmandilag** [besasm/EMGAATS#246]
From @andrey-nikolayev:

Error came up. Stopped editing and re-opened model, and error again came back up.

![image](https://cloud.githubusercontent.com/assets/11473179/12274986/6494dc6c-b922-11e5-9ca5-626414801f29.png)

Exception text:
```
System.Runtime.InteropServices.COMException (0x80040952): Exception from HRESULT: 0x80040952
   at ESRI.ArcGIS.Geodatabase.ITable.GetRow(Int32 OID)
   at BESASM.EMGAATS.UI.ArcMap.NetworkManager.GetRowForEntity(IEntity entity) in c:\Users\davidc\VS\EMGAATS2\BESASM.EMGAATS\UI.ArcMap\NetworkManager.cs:line 317
   at BESASM.EMGAATS.UI.ArcMap.EmgaatsExtension.PropertiesForm_EntityChanged(Object sender, EventArgs e) in c:\Users\davidc\VS\EMGAATS2\BESASM.EMGAATS\UI.ArcMap\EmgaatsExtension.cs:line 644
   at BESASM.EMGAATS.UI.PropertiesBaseForm.OnEntityChanged() in c:\Users\davidc\VS\EMGAATS2\BESASM.EMGAATS\UI\PropertiesBaseForm.cs:line 459
   at BESASM.EMGAATS.UI.PropertiesBaseForm.ValidateApplyAndClose() in c:\Users\davidc\VS\EMGAATS2\BESASM.EMGAATS\UI\PropertiesBaseForm.cs:line 365
   at BESASM.EMGAATS.UI.AreaPropertyEditor.OkButton_Click(Object sender, EventArgs e) in c:\Users\davidc\VS\EMGAATS2\BESASM.EMGAATS\UI\AreaPropertyEditor.cs:line 284
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

May be related to #236

**Comment by ahedhi** [comment]
Any chance you (@andrey-nikolayev) could provide the model gdb that produced this problem?

**Comment by andrey-nikolayev** [comment]
V:\9ESENMD00011 Dev Eng\CapacityCheck_4806_SE_16th\model\M5_Base
or
\\Cassio\ASM_Projects\9ESENMD00011 Dev Eng\CapacityCheck_4806_SE_16th\model\M5_Base

**Comment by ahedhi** [comment]
I worked with @andrey-nikolayev  and we could not reproduce, so I'm closing this. Feel free to reopen if it can be reproduced.

**Comment by andrey-nikolayev** [comment]
1.added area director (desire was to send all roof to planter)
2. but after recalling to insert Node to simulate planter with storate/weir/infiltrator, I tried to delete area director (but it won’t go away)
3.then updated “new” area director with Zero value, and “old” area director with original value for area; hit OK; error pop up (below are images and ‘details’ from error). Note, the “zero-area new” director was gone after re-opening the model.
